#!/usr/bin/env bash

CWD=$( pwd )
DOTFILES_DIR=${DOTFILES_DIR:-~/dotfiles}
SCRIPT_NAME=${0##*/}
CONFIG_FILE='config.json'

usage() {
  cat << EOF
usage: ${SCRIPT_NAME} <command>

Let me help you with your dotfiles.
All I need is:
  - git
  - jq
  - A ${CONFIG_FILE} in '${DOTFILES_DIR}'

Commands:
  link       Generate symlinks
  push       Push dotfiles
  pull       Pull dotfiles
  help       Display this message

EOF
}

error() {
  [[ -z "$1" ]] || printf '%s: %s\n' "${SCRIPT_NAME}" "$1"
  printf "Try '%s help' for more information.\\n" "${SCRIPT_NAME}"
  exit 1
} >&2

dots_link() {
  echo 'LINK'
}

dots_push() {
  echo 'PUSH'
}

dots_pull() {
  echo 'PULL'
}

parse_arguments() {
  COMMAND=$1

  case "${COMMAND}" in
    'link')
      dots_link
      ;;
    'push')
      dots_push
      ;;
    'pull')
      dots_pull
      ;;
    'help')
      usage
      exit
      ;;
    '')
      error 'Missing command'
      ;;
    *)
      error 'Invalid command'
  esac
}

parse_arguments "$@"
