#!/usr/bin/env bash

CWD=$( pwd )
DOTFILES_DIR=${DOTFILES_DIR:-~/dotfiles}
SCRIPT_NAME=${0##*/}

usage() {
  cat << EOF
usage: ${SCRIPT_NAME} <command>

Manage dotfiles accross machines.
Requires a dotsrc.json in ${DOTFILES_DIR}

Commands:
  init       Initialize dotfiles directory
  sync       Update dotfiles
  help       Display this message

EOF
}

error() {
  [[ -z "$1" ]] || printf '%s: %s\n' "${SCRIPT_NAME}" "$1"
  printf "Try '%s help' for more information.\\n" "${SCRIPT_NAME}"
  exit 1
} >&2

dots_sync() {
  cd "$DOTFILES_DIR"
  echo "Changed to $PWD"

  dotsfile="dotsrc.json"
  if ! [ -e "$dotsfile" ]; then
    echo "No $dotsfile found in $PWD"; exit 1
  fi

  dotsrc=$(<$dotsfile)
  echo "Read $dotsfile"

}

parse_arguments() {
  COMMAND=$1

  case "${COMMAND}" in
    'sync')
      dots_sync
      ;;
    'help')
      usage
      exit
      ;;
    '')
      error 'Missing command'
      ;;
    *)
      error 'Invalid command'
  esac
}

parse_arguments "$@"
